### ISSUE TITLE
[Bug]: Map Initialization Error

### ISSUE THREAD

**Issue by sonhoang-diqit** [googlemaps/flutter-navigation-sdk#351]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

When I call googleNavigationViewController.removeMarkers in the map page, I return to the previous page.
Then, I go to the map page again, I can't set the new marker, and the map doesn't show my current location, and the camera can't move. In the log terminal, it throws: 

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(viewNotFound, GoogleMapsNavigationViewHandlerError, Stacktrace: ["0   Runner                              0x0000000103112f24 $s25google_navigation_flutter9wrapError33_D276C471098E7CA5502A70E6362C3477LLySayypSgGypF + 472", "1   Runner                              0x0000000103116e64 $s25google_navigation_flutter15MapViewApiSetupC5setUp15binaryMessenger3apiySo013FlutterBinaryK0_p_AA0deF0_pSgtFZyypSg_yAJctcfU_ + 824", "2   Runner                              0x0000000103116888 $sypSgAAIegn_Iegng_yXlSgABIeyBy_IeyByy_TR + 144", "3   Flutter                             0x000000010af5e7cc __48-[FlutterBasicMessageChannel setMessageHandler:]_block_invoke + 160", "4   Flutter                             0x000000010a9d1768 ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3_fl10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 116", "5   libdispatch.dylib                   0x00000001062a8b98 _dispatch_call_block_and_release + 32", "6   libdispatch.dylib                   0x00000001062aa7bc _dispatch_client_callout + 20", "7   libdispatch.dylib                   0x00000001062bad58 _dispatch_main_queue_drain + 1084", "8   libdispatch.dylib                   0x00000001062ba90c _dispatch_main_queue_callback_4CF + 44", "9   CoreFoundation                      0x000000019cb8b710 00E76A98-210C-3CB5-930B-F236807FF24C + 354064", "10  CoreFoundation                      0x000000019cb88914 00E76A98-210C-3CB5-930B-F236807FF24C + 342292", "11  CoreFoundation                      0x000000019cb87cd8 CFRunLoopRunSpecific + 608", "12  GraphicsServices                    0x00000001e1a381a8 GSEventRunModal + 164", "13  UIKitCore                           0x000000019f1c090c 1741FA37-4E53-371E-8DAE-D611AAB0043D + 4237580", "14  UIKitCore                           0x000000019f2749d0 UIApplicationMain + 340", "15  Runner                              0x0000000102624570 main + 64", "16  dyld                                0x00000001c0239e4c 71846EAC-EE65-3697-BF7D-790B6A07DCDB + 249420"], null)
#0      MapViewApi.awaitMapReady (package:google_navigation_flutter/src/method_channel/messages.g.dart:2201:7)
<asynchronous suspension>
#1      GoogleMapsNavigationIOS._buildView.<anonymous closure> (package:google_navigation_flutter/src/google_navigation_flutter_ios.dart:100:9)
<asynchronous suspension>
flutter: isConnect = true
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(viewNotFound, GoogleMapsNavigationViewHandlerError, Stacktrace: ["0   Runner                              0x0000000103112f24 $s25google_navigation_flutter9wrapError33_D276C471098E7CA5502A70E6362C3477LLySayypSgGypF + 472", "1   Runner                              0x0000000103116e64 $s25google_navigation_flutter15MapViewApiSetupC5setUp15binaryMessenger3apiySo013FlutterBinaryK0_p_AA0deF0_pSgtFZyypSg_yAJctcfU_ + 824", "2   Runner                              0x0000000103116888 $sypSgAAIegn_Iegng_yXlSgABIeyBy_IeyByy_TR + 144", "3   Flutter                             0x000000010af5e7cc __48-[FlutterBasicMessageChannel setMessageHandler:]_block_invoke + 160", "4   Flutter                             0x000000010a9d1768 ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3_fl10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 116", "5   libdispatch.dylib                   0x00000001062a8b98 _dispatch_call_block_and_release + 32", "6   libdispatch.dylib                   0x00000001062aa7bc _dispatch_client_callout + 20", "7   libdispatch.dylib                   0x00000001062bad58 _dispatch_main_queue_drain + 1084", "8   libdispatch.dylib                   0x00000001062ba90c _dispatch_main_queue_callback_4CF + 44", "9   CoreFoundation                      0x000000019cb8b710 00E76A98-210C-3CB5-930B-F236807FF24C + 354064", "10  CoreFoundation                      0x000000019cb88914 00E76A98-210C-3CB5-930B-F236807FF24C + 342292", "11  CoreFoundation                      0x000000019cb87cd8 CFRunLoopRunSpecific + 608", "12  GraphicsServices                    0x00000001e1a381a8 GSEventRunModal + 164", "13  UIKitCore                           0x000000019f1c090c 1741FA37-4E53-371E-8DAE-D611AAB0043D + 4237580", "14  UIKitCore                           0x000000019f2749d0 UIApplicationMain + 340", "15  Runner                              0x0000000102624570 main + 64", "16  dyld                                0x00000001c0239e4c 71846EAC-EE65-3697-BF7D-790B6A07DCDB + 249420"], null)
#0      MapViewApi.awaitMapReady (package:google_navigation_flutter/src/method_channel/messages.g.dart:2201:7)
<asynchronous suspension>
#1      GoogleMapsNavigationIOS._buildView.<anonymous closure> (package:google_navigation_flutter/src/google_navigation_flutter_ios.dart:100:9)
<asynchronous suspension>`

### Flutter version

3.27.0

### Package version

0.5.2

### Native SDK versions

- [x] I haven't changed the version of the native SDKs

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.2 24C101 darwin-arm64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.99.3)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Son's iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for Son’s Ipad. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

### Steps to reproduce

1. on iOS device
2. Call .removeMarkers() method on the map page
3. Return to the previous page
4. Go to the map page

### Expected vs Actual Behavior

Can insert the new marker, and move camera

### Code Sample

```dart
// Example code here
```

**Comment by sonhoang-diqit** [comment]
I added marker with customer icon

**Comment by sonhvse61570** [comment]
Hi @jokerttu , 
I have updated the code in lib/src/google_navigation_flutter_ios.dart.
```
try {
    await viewAPI.awaitMapReady(viewId: viewId);
} catch (e) {}
onMapReady(viewId);
```

It works fine. But I don't know have other issues when by passing this exception.

**Comment by halid-wzfa** [comment]
I'm encountering an issue where the map sometimes fails to load. There’s no error output in the debug console by default, but when I enable "All Exceptions" and "Uncaught Exceptions". It seems related to the map setup process, possibly inside the awaitMapReady.
I get the following stack trace:
`Stacktrace:
["0   Runner.debug.dylib  0x0000000108dc6efc $s25google_navigation_flutter9wrapError...",  
 "1   Runner.debug.dylib  0x0000000108df56d4 $s25google_navigation_flutter15MapViewApiSetupC5setUp...",  
 ...
 "22  dyld                0x00000001d0fb2dcc ..."]
`

**Comment by halid-wzfa** [comment]
Hi @sonhvse61570 ,
Did you still get the error after updating the code?

**Comment by sonhoang-diqit** [comment]
Hi @halid-wzfa ,
I have updated to the newest code version.
It still throws this error **AND AND**, making my app not respond and cannot perform anything. (I have to delete app and reinstall (restart app can not bypass)).
You shouldn't upgrade to the newest version. The performance of this on iOS is lower than version 0.5.2.

**Comment by jokerttu** [comment]
Thank you for reporting this issue!
This situation most likely happens if view is created and destroyed right after, but needs deeper investigation to be sure.

If `awaitMapReady` fails `onMapReady` should not be called either as map cannot be controller with MapViewController.

As a workaround following should work:
```dart
try {
    await viewAPI.awaitMapReady(viewId: viewId);
    onMapReady(viewId);
} catch (e) {}
```

I will use my time to reproduce this and finding solution.

**Comment by sonhvse61570** [comment]
@jokerttu , 
I tried the version 0.6.0. But this error still happens.
At version 0.6.0. I detect some issues:

1.  On iOS, the first start navigation in 0.6.0 is too slow. Version 0.5.2 doesn't have this issue.
2. On iOS, version 0.6.0 has a big issue. That is the map, not a response, and can not perform other actions. I try to close the app and start again, it shows white screen and don't process anything. I have to re-install.
     - I reproduce this issue on iPhone 11, iPhone 12 and iPhone 12 pro with iOS 18.4

**Comment by rajeshbdabhi** [comment]
@jokerttu same issue still present into `google_navigation_flutter: 0.6.3` this version i verified here i attached error log

`
PlatformException: PlatformException(viewNotFound, GoogleMapsNavigationViewHandlerError, Stacktrace: ["0   Runner                              0x00000001056e6da8 _ZN11GMSx_proto25Arena13CopyConstructIN22GMSx_maps_gmm_geometry18RoutePositionProtoEEEPvPS0_PKv + 175884", "1   Runner                              0x00000001056fcc6c _ZN11GMSx_proto25Arena13CopyConstructIN22GMSx_maps_gmm_geometry18RoutePositionProtoEEEPvPS0_PKv + 265680", "2   Runner                              0x00000001056f59a4 _ZN11GMSx_proto25Arena13CopyConstructIN22GMSx_maps_gmm_geometry18RoutePositionProtoEEEPvPS0_PKv + 236296", "3   Flutter                             0x00000001081d6eb8 InternalFlutterGpu_Texture_AsImage + 34832", "4   Flutter                             0x0000000107c5bb1c Flutter + 441116", "5   libdispatch.dylib                   0x00000001a1f4dabc 25BD2FB8-CD70-3483-90E5-474788FDDD72 + 6844", "6   libdispatch.dylib                   0x00000001a1f677cc 25BD2FB8-CD70-3483-90E5-474788FDDD72 + 112588", "7   libdispatch.dylib                   0x00000001a1f84af0 25BD2FB8-CD70-3483-90E5-474788FDDD72 + 232176", "8   libdispatch.dylib                   0x00000001a1f5cea8 25BD2FB8-CD70-3483-90E5-474788FDDD72 + 69288", "9   libdispatch.dylib                   0x00000001a1f5cde4 _dispatch_main_queue_callback_4CF + 44", "10  CoreFoundation                      0x000000019975d5a0 44CF748C-19F2-31C4-A0F1-143E32768AF1 + 439712", "11  CoreFoundation                      0x000000019970fdf0 44CF748C-19F2-31C4-A0F1-143E32768AF1 + 122352", "12  CoreFoundation                      0x000000019970ed28 44CF748C-19F2-31C4-A0F1-143E32768AF1 + 118056", "13  GraphicsServices                    0x00000001ead15498 GSEventRunModal + 120", "14  UIKitCore                           0x000000019c48c838 ABE178BE-C241-3474-A192-70F042F71BF4 + 723000", "15  UIKitCore                           0x000000019c42afd0 UIApplicationMain + 336", "16  UIKitCore                           0x000000019c57193c ABE178BE-C241-3474-A192-70F042F71BF4 + 1661244", "17  Runner                              0x0000000104ab2260 Runner + 25184", "18  dyld                                0x000000019696db18 4E9F3B1E-8F53-3E3B-849C-950CA957C64B + 19224"], null)`
